# === Unbind keys ===

#unbind system defined prefix
unbind C-b

# === Bind keys to prefix table ===

# vertical split
bind -N "Vertical split" | split-window -h -c '#{pane_current_path}'

# horizontal split
bind -N "Horizzontal split" - split-window -v -c '#{pane_current_path}'

# source .tmux.conf file
bind -N "Reload tmux.conf file" r source-file /etc/tmux.conf \; display "Configuration Reloaded!"

# Change prefix
bind C-f send-prefix

# Send tmux buffer to system clipboards
bind -N "Copy tmux clipboard to system primary" P run "tmux show-buffer | xclip -sel p -i >/dev/null"\; display "Tmux clipboard sent to system clipboard!"
bind -N "Copy tmux clipboard to system clipboard" C run "tmux show-buffer | xclip -sel c -i >/dev/null"\; display "Tmux clipboard sent to system primary!"
bind -N "Copy tmux clipboard to all clipboard" a run "tmux show-buffer | xclip -sel p -i -f | xclip -sel c -i >/dev/null"\; display "Tmux clipboard sent to all clipboards!"

# Paste tmux clipboard using Ctrl-F + p
bind -N "Paste the most recent tmux buffer" p paste-buffer

# === Bind keys to root table ===

# switch panes using Alt-arrow without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# switch windows using Alt+Pag without prefix
bind -n M-PPage previous-window
bind -n M-NPage next-window

# === Set options  ===

# Vi mode for Copy mode
setw -g mode-keys vi

# Send tmux clipboard to system clipboard when pressing y in copy-mode
bind -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

# set prefix to control-f
set -g prefix C-f

# helps in faster key repetition
set -sg escape-time 0

# don't allow tmux to rename the window based on commands running
set-window-option -g allow-rename off

# Enable mouse and copy from mouse selection
set -g mouse on        # For tmux version 2.1 and up

# show host name and IP address on left side of status bar
set -g status-right-length 300
set -g status-right  "#[fg=#7400ff] #([ -d /proc/sys/net/ipv4/conf/eth0 ] && ip addr show dev eth0 | grep "inet[^6]" | awk '{print \"eth0: \" $2}') #[fg=#ffffff] #([ -d /proc/sys/net/ipv4/conf/wlp0s20f3 ] && ip addr show dev wlp0s20f3 | grep "inet[^6]" | awk '{print \"wlp0s20f3: \" $2}') #[fg=#d70000] #([ -d /proc/sys/net/ipv4/conf/tun0 ] && ip addr show dev tun0 | grep "inet[^6]" | awk '{print \"tun0: \" $2}') #[fg=black] \"#{=22:pane_title}\" %H:%M %d-%b-%y"
